# Generated by Django 6.1.1 on 2026-09-04 23:32
# Erweitert: Datenmigration überführt die 5 festen q_*-Felder in RatingAnswer.

import django.db.models.deletion
from django.db import migrations, models


def create_questions_and_convert(apps, schema_editor):
    """Legt die 5 Standardfragen an und überführt bestehende Ratings.

    Muss VOR den RemoveField-Operationen laufen, damit die q_*-Spalten
    noch lesbar sind. Historische Antworten bleiben so erhalten.
    """
    RatingQuestion = apps.get_model('core', 'RatingQuestion')
    Rating = apps.get_model('core', 'Rating')
    RatingAnswer = apps.get_model('core', 'RatingAnswer')

    question_fields = [
        ('Wie interessant ist der Unterricht?', 'interest', 1),
        ('Wie produktiv ist der Unterricht?', 'productivity', 2),
        ('Wie fair bewertet die Lehrkraft?', 'fairness', 3),
        ('Wie ist die Arbeitsatmosphäre?', 'atmosphere', 4),
        ('Wie ist die Digitalisierung im Unterricht?', 'digitalization', 5),
    ]
    questions = {}
    for text, key, order in question_fields:
        q, _ = RatingQuestion.objects.get_or_create(
            key=key, defaults={'text': text, 'order': order, 'is_active': True}
        )
        questions[key] = q

    mapping = {
        'q_interest': 'interest',
        'q_productivity': 'productivity',
        'q_fairness': 'fairness',
        'q_atmosphere': 'atmosphere',
        'q_digitalization': 'digitalization',
    }
    for rating in Rating.objects.all():
        for q_field, key in mapping.items():
            value = getattr(rating, q_field, None)
            if value is not None:
                RatingAnswer.objects.create(
                    rating_id=rating.pk,
                    question=questions[key],
                    value=value,
                )


def reverse_convert(apps, schema_editor):
    """Schreibt Antworten zurück in die (wieder hinzugefügten) q_*-Spalten."""
    RatingQuestion = apps.get_model('core', 'RatingQuestion')
    Rating = apps.get_model('core', 'Rating')
    RatingAnswer = apps.get_model('core', 'RatingAnswer')

    mapping = {
        'q_interest': 'interest',
        'q_productivity': 'productivity',
        'q_fairness': 'fairness',
        'q_atmosphere': 'atmosphere',
        'q_digitalization': 'digitalization',
    }
    for rating in Rating.objects.all():
        for q_field, key in mapping.items():
            answer = RatingAnswer.objects.filter(
                rating=rating, question__key=key
            ).first()
            setattr(rating, q_field, answer.value if answer else None)
        rating.save()
    RatingAnswer.objects.all().delete()
    RatingQuestion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('key', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RatingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.rating')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.ratingquestion')),
            ],
            options={
                'ordering': ['question__order'],
                'constraints': [models.UniqueConstraint(fields=('rating', 'question'), name='unique_rating_question_answer')],
            },
        ),
        migrations.RunPython(create_questions_and_convert, reverse_convert),
        migrations.RemoveField(
            model_name='rating',
            name='q_atmosphere',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='q_digitalization',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='q_fairness',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='q_interest',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='q_productivity',
        ),
    ]
