# Generated by Django 6.1.1 on 2026-09-05 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ratingquestion_remove_rating_q_atmosphere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherachievement',
            name='manually_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AchievementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('top_n_rank', 'Top-N im Gesamt-Ranking'), ('category_score_above', 'Kategorie-Score über Schwellenwert')], max_length=30)),
                ('threshold_value', models.FloatField(default=0)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.achievement')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.ratingquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRankSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('category_scores', models.JSONField(default=dict)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.teacher')),
            ],
            options={
                'ordering': ['teacher', '-date'],
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
