# Generated by Django 6.1.1 on 2026-09-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacherachievement_manually_removed_achievementrule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherscore',
            name='avg_atmosphere',
        ),
        migrations.RemoveField(
            model_name='teacherscore',
            name='avg_digitalization',
        ),
        migrations.RemoveField(
            model_name='teacherscore',
            name='avg_fairness',
        ),
        migrations.RemoveField(
            model_name='teacherscore',
            name='avg_interest',
        ),
        migrations.RemoveField(
            model_name='teacherscore',
            name='avg_productivity',
        ),
    ]
