# Generated by Django 6.1.1 on 2026-09-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_teacherscore_avg_atmosphere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementrule',
            name='condition_type',
            field=models.CharField(choices=[('top_n_rank', 'Top-N im Gesamt-Ranking'), ('category_score_above', 'Kategorie-Score über Schwellenwert'), ('category_score_below', 'Kategorie-Score unter Schwellenwert')], max_length=30),
        ),
    ]
