"""
Django settings for bal project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

from pathlib import Path

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-r&0uz1spgssn4@ju+!w!-@1gd3nws+&f96)zfzjdq-fdxsrtcy',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

def _csv_setting(name, default):
    return [x.strip() for x in os.environ.get(name, default).split(',') if x.strip()]


ALLOWED_HOSTS = _csv_setting('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')

CSRF_TRUSTED_ORIGINS = _csv_setting('DJANGO_CSRF_TRUSTED_ORIGINS', '')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bal.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploaded images)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email (console backend for MVP; swap for real SMTP later)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Login / redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Cache: FileBasedCache ist worker-übergreifend geteilt (wichtig, weil
# Gunicorn mit mehreren Workern läuft und LocMem pro Worker zählen würde).
# Für Multi-Server-Betrieb Redis/Memcached eintragen.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.environ.get('BAL_CACHE_DIR', str(BASE_DIR / 'cache')),
        'OPTIONS': {'MAX_ENTRIES': 10000},
    }
}

# Rate Limiting gegen Bots (core/ratelimit.py). Formate: "<n>/<s|m|h|d>".
# Über Env je Umgebung anpassbar, z.B. BAL_RL_SIGNUP_HOUR=20/h.
BAL_RATELIMIT_ENABLE = os.environ.get('BAL_RATELIMIT_ENABLE', 'True').lower() in ('1', 'true', 'yes')
BAL_RATELIMITS = {
    'signup_ip_hour': os.environ.get('BAL_RL_SIGNUP_HOUR', '10/h'),
    'signup_ip_day': os.environ.get('BAL_RL_SIGNUP_DAY', '30/d'),
    'login_ip_minute': os.environ.get('BAL_RL_LOGIN_MINUTE', '10/m'),
    'login_ip_hour': os.environ.get('BAL_RL_LOGIN_HOUR', '30/h'),
    'rating_user_minute': os.environ.get('BAL_RL_RATING_USER_MINUTE', '10/m'),
    'rating_user_hour': os.environ.get('BAL_RL_RATING_USER_HOUR', '60/h'),
    'rating_ip_hour': os.environ.get('BAL_RL_RATING_IP_HOUR', '200/h'),
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
